FROM node:20-alpine AS deps
    WORKDIR /app
    COPY package.json package-lock.json* ./
    COPY prisma ./prisma          
    RUN npm install

FROM node:20-alpine AS builder
    WORKDIR /app
    COPY --from=deps /app/node_modules ./node_modules
    COPY . .
    RUN npx prisma generate
    RUN npm run build

FROM node:20-alpine AS runner
    WORKDIR /app
    ENV NODE_ENV=production
    COPY package.json package-lock.json* ./
    COPY prisma ./prisma
    RUN npm install --omit=dev
    COPY --from=builder /app/dist ./dist
    EXPOSE 3001
    CMD ["node", "dist/main.js"]